name: 🎨 New Background Request
description: Request a new animated background to be added to the library
title: '[Background Request]: '
labels: ['enhancement', 'background-request']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new background! Please fill out the information below to help us understand what you'd like to see added.

  - type: input
    id: background-name
    attributes:
      label: Background Name
      description: What would you like to call this background?
      placeholder: e.g., "Plasma Wave", "Cosmic Nebula", "Aurora Borealis"
    validations:
      required: true

  - type: input
    id: shader-link
    attributes:
      label: Shader Source Link
      description: Link to the shader (e.g., Shadertoy, GLSL Sandbox, or other source)
      placeholder: https://www.shadertoy.com/view/...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what the background looks like and why you think it would be a great addition
      placeholder: |
        This is a mesmerizing plasma wave effect with smooth color transitions. 
        It would work great as a subtle, non-distracting background for apps.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Preview
      description: |
        Please provide a screenshot or GIF showing what the background looks like.
        You can drag and drop images here, or paste a link.
      placeholder: Drag and drop images here or paste links
    validations:
      required: false

  - type: dropdown
    id: animation-type
    attributes:
      label: Animation Type
      description: What type of animation does this background have?
      options:
        - Static (no animation)
        - Time-based animation (continuous)
        - Interactive (responds to touch/gestures)
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Performance Complexity
      description: How computationally intensive is this shader?
      options:
        - Low (simple effects)
        - Medium (moderate complexity)
        - High (complex calculations)
        - Not sure
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful (color schemes, customization ideas, use cases, etc.)
      placeholder: This would be perfect for meditation apps or calming interfaces
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to implement this background?
      options:
        - label: I'd like to implement this myself and submit a PR
          required: false

  - type: markdown
    attributes:
      value: |
        ---

        **Note**: Not all shader effects may be feasible to port to React Native or may require significant modification. 
        We'll do our best to evaluate each request and implement what's possible while maintaining good performance.
